#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path
import re


ROOTS = [
    Path.home() / ".codex" / "skills",
    Path.home() / ".agents" / "skills",
]

OUTFILE = Path(__file__).resolve().parent.parent / "references" / "installed-skills.md"


def parse_frontmatter(text: str) -> tuple[str | None, str | None]:
    match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not match:
        return None, None
    body = match.group(1)
    name_match = re.search(r'^name:\s*"?([^\n"]+)"?\s*$', body, re.M)
    name = name_match.group(1).strip() if name_match else None
    desc = None
    lines = body.splitlines()
    for idx, line in enumerate(lines):
        if not line.startswith("description:"):
            continue
        value = line.split(":", 1)[1].strip()
        if value and value not in {"|", ">"}:
            desc = value.strip('"')
            break
        block: list[str] = []
        for next_line in lines[idx + 1 :]:
            if next_line.startswith("  "):
                block.append(next_line.strip())
                continue
            break
        desc = " ".join(block).strip() or None
        break
    return name, desc


def collect_skills() -> list[tuple[str, str, str]]:
    found: dict[str, tuple[str, str, str]] = {}
    for root in ROOTS:
        if not root.exists():
            continue
        for skill_file in root.glob("*/SKILL.md"):
            text = skill_file.read_text(encoding="utf-8", errors="ignore")
            name, desc = parse_frontmatter(text)
            if not name:
                continue
            short_desc = (desc or "").replace("\n", " ").strip()
            found[name] = (name, short_desc, str(skill_file))
    return sorted(found.values(), key=lambda item: item[0].lower())


def main() -> None:
    skills = collect_skills()
    lines = [
        "# Installed Skills",
        "",
        "Auto-generated by `scripts/refresh_installed_skills.py`.",
        "",
    ]
    for name, desc, path in skills:
        lines.append(f"## ${name}")
        lines.append(f"- Path: `{path}`")
        if desc:
            lines.append(f"- Description: {desc}")
        lines.append("")
    OUTFILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTFILE}")
    print(f"Skills indexed: {len(skills)}")


if __name__ == "__main__":
    main()
